### PR TITLE
modrinth  （；へ：） please

### PR DESCRIPTION
**Pull request by lenrik1589**

### CODE REVIEW

**Comment by Gakuto1112** [comment]
Thanks for your advice, but I don't know why I should use Modrinth insted of CurseForge. Is there a problem with CurseForge?
It's not that I don't like Modrinth, but I don't know anything about Modrinth.

**Review by Gakuto1112 — COMMENTED** [review]
Reviewed. Please answer my question.

**Comment by Gakuto1112** [comment]
Closed without merged. Reason:
- README changed dramatically from when this pull request posted.
- You did not answer my question and it passed one week since I asked a question.
- I think that CurseForge is more famous than Modrinth.

**Comment by BlueFunny19** [comment]
Modrinth or CurseForge are dedicated to posting Mods, while content like Figura models can be posted in a dedicated subchannel of the official Figura Discord server
You can check out their official Discord server: https://discord.com/invite/figuramc

**Pull request closed without merging**
